spring.application.name=polyglot

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/polyglot
spring.datasource.username=polyglot
spring.datasource.password=polyglot

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true
